spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 15

app:
  debug: false

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME:medicaler-image}
    region: ${AWS_REGION:ap-southeast-2}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
